server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Never cache JS and CSS files
    location ~* \.(js|css)$ {
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location /api/ {
        resolver 127.0.0.11 valid=30s;
        set $backend http://backend:8000;
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass $backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}